### PR TITLE
(#2176379) Job deserialization and handling fixes

### PR DESCRIPTION
**Pull request by msekletar**

### CODE REVIEW

**Comment by msekletar** [comment]
@rmetrich the question is how to handle problem described in commit message https://github.com/redhat-plumbers/systemd-rhel7/pull/144/commits/9b403d5866d35aa31ffb985de193c70c171e5c64 ? Basically, the code reverted by that commit was introduced to prevent races and fix https://bugzilla.redhat.com/show_bug.cgi?id=1351793. If we just blindly backport that commit it will introduce a regression. The solution mentioned also in the commit message is to split deserialization and state synchronization (catchup). However, we have absolutely zero support for that in RHEL-7 systemd code base and code changes for that are quite substantial.

**Comment by msekletar** [comment]
@dtardon since you are author https://github.com/systemd/systemd/pull/8803, do you have an idea what Lennart meant when he said "Memory management is borked for this, ..." in commit message https://github.com/redhat-plumbers/systemd-rhel7/commit/9b403d5866d35aa31ffb985de193c70c171e5c64? Do you know what exactly was wrong in terms of MM with the original code?

**Comment by dtardon** [comment]
> @dtardon since you are author [systemd/systemd#8803](https://github.com/systemd/systemd/pull/8803), do you have an idea what Lennart meant when he said "Memory management is borked for this, ..." in commit message [9b403d5](https://github.com/redhat-plumbers/systemd-rhel7/commit/9b403d5866d35aa31ffb985de193c70c171e5c64)?

Most likely https://github.com/systemd/systemd/issues/10716, which the commit references as fixed.

**Comment by dtardon** [comment]
> @dtardon since you are author [systemd/systemd#8803](https://github.com/systemd/systemd/pull/8803), do you have an idea what Lennart meant when he said "Memory management is borked for this, ..." in commit message [9b403d5](https://github.com/redhat-plumbers/systemd-rhel7/commit/9b403d5866d35aa31ffb985de193c70c171e5c64)?

Most likely https://github.com/systemd/systemd/issues/10716, which the commit references as fixed.

**Comment by Forrest-ly** [comment]
@msekletar hi，will this work continue?

**Pull request closed without merging**
