### PR TITLE
(#1804757) mount units err state

### PR DESCRIPTION
**Pull request by jsynacek**

### CODE REVIEW

**Comment by mrc0mmand** [comment]
Full backtrace from one of the segfaulting tests in Travis (also recompiled with `CFLAGS="-O0 -g"):

```
Core was generated by `./test-engine'.
Program terminated with signal 11, Segmentation fault.
#0  0x0000557e2d8a763d in MOUNT (u=0x12) at src/core/unit.h:474
474	DEFINE_CAST(MOUNT, Mount);
Missing separate debuginfos, use: debuginfo-install audit-libs-2.8.5-4.el7.x86_64 glibc-2.17-292.el7.x86_64 libattr-2.4.46-13.el7.x86_64 libblkid-2.23.2-61.el7_7.1.x86_64 libcap-2.22-10.el7.x86_64 libcap-ng-0.7.5-4.el7.x86_64 libmount-2.23.2-61.el7_7.1.x86_64 libselinux-2.5-14.1.el7.x86_64 libuuid-2.23.2-61.el7_7.1.x86_64 pam-1.1.8-22.el7.x86_64 pcre-8.32-17.el7.x86_64
(gdb) bt full
#0  0x0000557e2d8a763d in MOUNT (u=0x12) at src/core/unit.h:474
No locals.
#1  0x0000557e2d8ac258 in mount_setup_unit (m=0x557e2f147180, what=0x557e2f158cd0 "configfs", where=0x557e2f158c40 "/sys/kernel/config", 
    options=0x557e2f15a6b0 "rw,relatime", fstype=0x557e2f14a410 "configfs", set_flags=false) at src/core/mount.c:1439
        e = 0x0
        w = 0x0
        o = 0x0
        f = 0x0
        load_extras = false
        p = 0x7ffe242b1fe0
        delete = 20
        changed = false
        u = 0x12
        r = 21886
        __PRETTY_FUNCTION__ = "mount_setup_unit"
        __func__ = "mount_setup_unit"
#2  0x0000557e2d8acb77 in mount_load_proc_self_mountinfo (m=0x557e2f147180, set_flags=false) at src/core/mount.c:1625
        device = 0x557e2f1618e0 "configfs"
        k = 0
        path = 0x557e2f14a330 "/sys/kernel/config"
        options = 0x557e2f15a6b0 "rw,relatime"
        fstype = 0x557e2f14a410 "configfs"
        d = 0x557e2f158cd0 "configfs"
        p = 0x557e2f158c40 "/sys/kernel/config"
        fs = 0x557e2f1601c0
        t = 0x557e2f152a70
        i = 0x557e2f14a9f0
        r = 0
        __PRETTY_FUNCTION__ = "mount_load_proc_self_mountinfo"
        __func__ = "mount_load_proc_self_mountinfo"
#3  0x0000557e2d8acf4b in mount_enumerate (m=0x557e2f147180) at src/core/mount.c:1705
        r = 0
        __PRETTY_FUNCTION__ = "mount_enumerate"
#4  0x0000557e2d86f245 in manager_enumerate (m=0x557e2f147180) at src/core/manager.c:1078
        q = 0
        r = 0
        c = UNIT_MOUNT
        __PRETTY_FUNCTION__ = "manager_enumerate"
        __func__ = "manager_enumerate"
#5  0x0000557e2d86f991 in manager_startup (m=0x557e2f147180, serialization=0x0, fds=0x0) at src/core/manager.c:1253
        r = 0
        q = 21886
        __PRETTY_FUNCTION__ = "manager_startup"
#6  0x0000557e2d858eb3 in main (argc=1, argv=0x7ffe242b2318) at src/test/test-engine.c:47
        err = {name = 0x0, message = 0x0, _need_free = 0}
        m = 0x557e2f147180
        a = 0x0
        b = 0x0
        c = 0x0
        d = 0x0
        e = 0x0
        g = 0x0
        h = 0x0
        serial = 0x0
        fdset = 0x0
---Type <return> to continue, or q <return> to quit---
        j = 0x0
        r = 0
        __PRETTY_FUNCTION__ = "main"
        __func__ = "main"

```

**Comment by mrc0mmand** [comment]
Ah, I see, `u` is not assigned, yet. Extrapolating from the [original patch](https://github.com/systemd/systemd/commit/6d7e89b07065b8c49af47aaf1ccc336d017fc3a2) I guess the assignment should be somewhere around this part:

https://github.com/systemd-rhel/rhel-7/blob/8adebe27c7604ca62ff833bfa281d11f4be431bd/src/core/mount.c#L1470-L1491

**Comment by jsynacek** [comment]
v2.

**Review by dtardon — APPROVED** [review]
LGTM

**Pull request merged**
