### PR TITLE
(#1733998) don't skip ExecStopPost on failure

### PR DESCRIPTION
**Pull request by dtardon**

### CODE REVIEW

**Comment by dtardon** [comment]
Note: the 2nd patch is not strictly necessary to fix #1733998 (which only speaks about Type=forking services), but it fixes the same problem for Type=notify. It's also more complex (and thus more prone to break things). I'll leave it for discussion whether to include it or not.

**Comment by mrc0mmand** [comment]
So, there appears to be a race condition caused by (probably) initrd-related backports from #36, which results in a system ending up in an emergency mode under certain conditions, with:

```
# systemctl status initrd-switch-root
● initrd-switch-root.service - Switch Root
   Loaded: loaded (/usr/lib/systemd/system/initrd-switch-root.service; static; vendor preset: enabled)
   Active: failed (Result: signal) since Fri 2019-09-20 16:48:14 BST; 5min ago
  Process: 381 ExecStart=/usr/bin/systemctl --no-block --force switch-root /sysroot (code=killed, signal=TERM)
 Main PID: 381 (code=killed, signal=TERM)

Sep 20 16:48:14 n30.dusty.ci.centos.org systemctl[381]: Failed to determine peer security context: Protocol not available
Sep 20 16:48:14 n30.dusty.ci.centos.org systemctl[381]: Switching root - root: /sysroot; init: n/a
Sep 20 16:48:14 n30.dusty.ci.centos.org systemctl[381]: Got unexpected auxiliary data with level=1 and type=2
Sep 20 16:48:14 systemd-testsuite systemd[1]: Installed new job initrd-switch-root.service/stop as 177
```

Full journal log until the emergency mode: http://artifacts.ci.centos.org/systemd/initrd-issue.log

**Comment by msekletar** [comment]
I've reviewed the backport and it LGTM, however, this one is particularly tricky and I might have missed something.

@jsynacek please have a look as well.

**Review by jsynacek — APPROVED** [review]
LGTM.

**Pull request merged**
